# Generated by Django 5.2.13 on 2026-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_subscription_delivery_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='centro_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estado_suministro',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('EN_PREPARACION', 'En preparación'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelar')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_entrega_deseada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_centro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_pedido',
            field=models.CharField(choices=[('COMPRA_DIRECTA', 'Compra Directa'), ('PEDIDO_PLANIFICADO', 'Pedido Planificado')], default='COMPRA_DIRECTA', max_length=30),
        ),
    ]
