# Generated by Django 5.2.13 on 2026-06-17 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_fecha_respuesta_productor_order_frecuencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecobox',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
