# Generated by Django 5.2.13 on 2026-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ecobox_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estado_productor',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN_PREPARACION', 'En preparación'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='observaciones_productor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado_suministro',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente de aceptación'), ('PARCIALMENTE_ACEPTADO', 'Parcialmente aceptado'), ('CONFIRMADO', 'Confirmado'), ('EN_PREPARACION', 'En preparación'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_PARCIAL', 'Rechazado parcialmente'), ('CANCELADO', 'Cancelar')], default='PENDIENTE', max_length=30, null=True),
        ),
    ]
