# Generated by Django 5.2.13 on 2026-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_estado_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo_pedido',
            field=models.CharField(choices=[('COMPRA_DIRECTA', 'Compra Directa'), ('PEDIDO_PLANIFICADO', 'Pedido Planificado'), ('NORMAL', 'Compra Normal'), ('PLANIFICADO_RESTAURACION', 'Pedido Planificado Restauración')], default='NORMAL', max_length=30),
        ),
    ]
