# Generated by Django 5.2.13 on 2026-06-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_tipo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ecobox_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ecobox_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proxima_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
