# Generated by Django 5.2.13 on 2026-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Lacteos', 'Lácteos'), ('Huevos', 'Huevos'), ('Miel', 'Miel'), ('Bebidas', 'Bebidas'), ('Conservas', 'Conservas'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_disponible_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_disponible_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_reserva_futura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='temporada',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Verano', 'Verano'), ('Otoño', 'Otoño'), ('Invierno', 'Invierno'), ('Todo el año', 'Todo el año')], default='Todo el año', max_length=50),
        ),
    ]
