# Generated by Django 5.2.13 on 2026-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producto_activo_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='observaciones_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
