# Generated by Django 5.2.13 on 2026-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre_centro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='observaciones_centro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='persona_responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_centro',
            field=models.CharField(blank=True, choices=[('COLEGIO', 'Colegio'), ('HOSPITAL', 'Hospital'), ('RESIDENCIA', 'Residencia'), ('COMEDOR', 'Comedor'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PRODUCTOR', 'Productor'), ('RESTAURACION', 'Restauración Colectiva')], default='CLIENTE', max_length=20),
        ),
    ]
