# Generated by Django 5.2.13 on 2026-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_nombre_centro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento_centro',
            field=models.FileField(blank=True, null=True, upload_to='documentos_centros/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado_validacion_centro',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_subida_documento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_validacion_centro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='observaciones_validacion_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
